# Generated by OrchestKit Claude Plugin
# Created: 2026-07-14

"""ASCII logo banner and startup display for AIBA CLI.

Generates the AIBA logo from the PNG via ASCII art and provides
a beautiful startup screen similar to Claude Code's welcome banner.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

from src.services import rendering as R

_LOGO_PATH = Path(__file__).resolve().parent.parent.parent / "docs" / "assets" / "aiba_logo.png"

# ── Pre-built ASCII logo (generated from aiba_logo.png) ──────────────
# Width: 70 chars, dark-to-light character gradient

_ASCII_LOGO = """\
                          CCCCCCCCCCCCCCCCCC
                    CCCCJJUJJJJCCCCCCCJCJJJJJJCCCJ
                JCCUUUJCCCCCCCCJUUJJJCCJUUUUJCCJUUUCCC
             CCUUJCCCCCCCCCCJUCZk#MW&&8M#okq0JCCCCCCJUUCJ
           CUUJCCCCCCCCCCCCJQb8$$$$$$$$$$$$$@OJCCCCCCCCCUUJJ
        CJUJCCCCCCCCCCCCCCJ0@$$B&#hhkkh$$$$$$&CCCCCCCCCCCCJUJJ
       JUCCCCCCCCCCCCCCCCCUk$8_;.      }B$$$$$dUCCCCCCCCCCCCCUJ
     JUJCCCCCCCCCCCCCCCCCJQ%$O  1q0|`.. ]$$$$$%CCCCCCCCCCCCCCCCUJ
    JUCCCCCCCCCCCCCCCCCCCCW$B_ u$$$$(.'' d$$$$$oJCCCCCCCCCCCCCCCUJ
   JJCCCCCCCCCCCCCCCCCCCUp$$t )$@$@$Q .'.)$$$$$$OJCCCCCCCCCCCCCCCJJ
  CJCCCCCCCCCCCCCCCCCCCCC8$%^<%$$$$$B~ ' ^&$$$$$kUCCCCCCCCCCCCCCCCJJ
 CUCCCCCCCCCCCCCCCCCCCCJo$B].o$$$$$@$q..' Y$@$$$BLCCCCCCCCCCCCCCCUC
 CCCCCCCCCCCCCCCCCCCCCUw$$z )$@$$$wq$$?.' !@$$$$$hUCCCCCCCCCCCCCCCJ
CUCCCCCCCCCCCCCCCCCCCCC8$W;`a$$$$kXC%$Z .. Z$$$$$$0JCCCCCCCCCCCCCCJC
CJCCCCCCCCCCCCCCCCCCCUb$$| 1$$$$$wO0#$$j ' {$$$$$$hUCCCCCCCCCCCCCCJC
CJCCCCCCCCCCCCCCCCCCJOB$b''w@@@$$$$$$$@$] ''p$$$$$@0JCCCCCCCCCCCCCJC
CJCCCCCCCCCCCCCCCCCCJ&$@~ ^%$$$$$$$$$$$$C ' i@$$$$$MUCCCCCCCCCCCCCJC
 UCCCCCCCCCCCCCCCCCUd$$C '.?(((({?+>i!+x+..' u$$$$$$ZJCCCCCCCCCCCCUC
 CJCCCCCCCCCCCCCCCJQ@$&;..         .:I;,^  ..`h$$$$$&JCCCCCCCCCCCCC
  UCCCCCCCCCCCCCCCUo$$/ ' !/juXCZdo8$$$$%Q'.' ?$$$$$$aJCCCCCCCCCCUC
  CUCCCCCCCCCCCCCJO$$q '. d$$$$$&bdwZOLo$$1 ' `&$$$$$$0JCCCCCCCCUC
   JUCCCCCCCCCCCCUa$$> ' /$@@@@BCYUUJJU0$$h..' O$@$$$&JCCCCCCCCUJ
    JUCCCCCCCCCCUm$$c '''o$$$$$oULCCCCCJh$$r . Ih$$$$mUCCCCCCCCUJ
     CJJCCCCCCCCC8$q    ?$$$$$%QJCCCCCCCUk$B<`^'i&$$&JCCCCCCCCJJJ
       JUJCCCCCUh$B~,>?/M$$$BhLJCCCCCCCJ%$B&&&M@$$ZJCCCCCCCUJ
         JJUCCCJ%$$&%$$$@&kwLUCCCCCCCCCC0ZmwwwwmZZCCCCCCJUJ
           JCUJJwppdwOQCCJUUJCCCCCCCCCCCCCJJUUUUUJJJCCCJUCJ
              JCYYUUUJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCJUUCCJ
                 CCCUUUJCCCCCCCCCCCCCCCCCCCCCJJUUUJCC
                     CCCCCJJUUJJJJJJJJJJUUJJCCCCC
                            CCCCCCCCCCCCCC"""


def _generate_ascii_logo(width: int = 70) -> str:
    """Generate ASCII art from the PNG logo file.

    Falls back to the pre-built constant if the PNG is not available.
    """
    if not _LOGO_PATH.is_file():
        return _ASCII_LOGO

    try:
        img = Image.open(str(_LOGO_PATH))
        if img.mode != "RGBA":
            img = img.convert("RGBA")

        aspect = img.height / img.width
        new_h = int(aspect * width * 0.45)
        import PIL.Image as PILImage
        img = img.resize((width, new_h), PILImage.Resampling.LANCZOS)
        import warnings
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", message="Image.Image.getdata")
            pixels = list(img.getdata())  # pyright: ignore[reportArgumentType]

        chars = "$@B%8&WM#oahkbdpqwmZO0QLCJUYXzcvunxrjft/|()1{}[]?-_+~<>i!lI;:,^`'. "

        rows: list[str] = []
        for y in range(new_h):
            row: list[str] = []
            for x in range(width):
                r, g, b, a = pixels[y * width + x]
                if a < 128:
                    row.append(" ")
                    continue
                gray = 0.299 * r + 0.587 * g + 0.114 * b
                idx = min(int(gray / 255 * (len(chars) - 1)), len(chars) - 1)
                row.append(chars[idx])
            rows.append("".join(row))
        return "\n".join(rows)
    except Exception:
        return _ASCII_LOGO


def print_startup_banner() -> None:
    """Print the startup banner with ASCII logo and tagline.

    Mimics Claude Code's clean startup look:
    - ASCII logo (cyan/teal)
    - Version string
    - Tagline
    - Thin divider
    """
    logo = _generate_ascii_logo(70)
    version = __import__("importlib.metadata", fromlist=["version"]).version("aiba") \
        if __import__("importlib.util", fromlist=["find_spec"]).find_spec("aiba") else "0.2.0"

    R.console.print()
    R.console.print(f"[bold cyan]{logo}[/bold cyan]")
    R.console.print()
    R.console.print(f"  [bold cyan]AIBA[/bold cyan]  [dim]v{version}[/dim]")
    R.console.print("  [dim]Autonomous Internet Browsing Agent[/dim]")
    R.console.print()


def print_session_resume_banner(agent_name: str, message_count: int) -> None:
    """Print a compact banner when resuming a session."""
    R.divider()
    R.console.print(
        f"  [cyan]Resuming[/cyan] [bold]{agent_name}[/bold] "
        f"([dim]{message_count} messages[/dim])",
    )
    R.divider()
