# Generated by OrchestKit Claude Plugin
# Created: 2026-07-14

"""Live-updating status display during agent execution.

Inspired by Claude Code's status line — shows spinner, agent name,
model name, elapsed time, and resource usage.
"""

from __future__ import annotations

import threading
import time
from datetime import UTC, datetime
from typing import Any

from rich.live import Live
from rich.spinner import Spinner
from rich.table import Table

from src.services.rendering import console


class AgentStatus:
    """Live-updating status display for agent execution.

    Usage:
        with AgentStatus(console, agent_name="Agent", model_name="gemini-3.5-flash") as status:
            result = agent_fn(...)
            status.update(tokens=..., cost=...)
    """

    def __init__(
        self,
        agent_name: str = "Agent",
        model_name: str = "",
        total_budget: Any | None = None,
    ) -> None:
        self.agent_name = agent_name
        self.model_name = model_name
        self.total_budget = total_budget
        self.start_time = datetime.now(UTC)
        self._stop_event = threading.Event()
        self._live: Live | None = None
        self._spinner = Spinner("dots", style="cyan")
        self._tokens: int = 0
        self._cost: float = 0.0
        self._status_text: str = "Running..."

    def update(
        self,
        *,
        tokens: int | None = None,
        cost: float | None = None,
        status_text: str | None = None,
    ) -> None:
        """Update status display fields."""
        if tokens is not None:
            self._tokens = tokens
        if cost is not None:
            self._cost = cost
        if status_text is not None:
            self._status_text = status_text

    def _build_table(self) -> Table:
        """Build the current status table."""
        elapsed = (datetime.now(UTC) - self.start_time).total_seconds()
        elapsed_str = f"{elapsed:.0f}s" if elapsed < 120 else f"{elapsed / 60:.1f}m"

        table = Table(
            show_header=False,
            show_edge=False,
            show_lines=False,
            padding=(0, 1),
            box=None,
        )
        table.add_column(width=2)  # spinner
        table.add_column(style="bold")
        table.add_column(style="dim")
        table.add_column()  # model
        table.add_column(style="dim")
        table.add_column()  # elapsed

        model_display = f"Model: {self.model_name}" if self.model_name else ""

        table.add_row(
            self._spinner,
            self.agent_name,
            "│",
            model_display,
            "│",
            elapsed_str,
        )

        # Second row for tokens/cost if available
        if self._tokens or self._cost:
            info_parts = []
            if self._tokens:
                info_parts.append(f"Tokens: {self._tokens:,}")
            if self._cost:
                info_parts.append(f"Cost: ${self._cost:.4f}")
            if info_parts:
                table.add_row("", "  " + "  │  ".join(info_parts), "", "", "", "", style="dim")

        if self._status_text != "Running...":
            table.add_row("", f"  {self._status_text}", "", "", "", "", style="dim italic")

        return table

    def __enter__(self) -> AgentStatus:
        """Start the live display."""
        self._live = Live(
            self._build_table(),
            console=console,
            refresh_per_second=10,
            transient=True,
        )
        self._live.__enter__()
        self._updater_thread = threading.Thread(target=self._refresh_loop, daemon=True)
        self._updater_thread.start()
        return self

    def __exit__(self, *args: Any) -> None:
        """Stop the live display."""
        self._stop_event.set()
        if self._updater_thread.is_alive():
            self._updater_thread.join(timeout=1.0)
        if self._live:
            self._live.__exit__(*args)

    def _refresh_loop(self) -> None:
        """Continuously refresh the display."""
        while not self._stop_event.is_set():
            if self._live:
                self._live.update(self._build_table())
            time.sleep(0.1)


def agent_status_display(
    agent_name: str = "Agent",
    model_name: str = "",
    total_budget: Any | None = None,
) -> AgentStatus:
    """Convenience context manager for AgentStatus.

    Usage:
        with agent_status_display(agent_name="Agent", model_name="gemini-3.5-flash"):
            ...
    """
    return AgentStatus(
        agent_name=agent_name,
        model_name=model_name,
        total_budget=total_budget,
    )
