# Generated by OrchestKit Claude Plugin
# Created: 2026-07-14

"""Interactive wizard for AIBA setup — Rich-powered version of screens.py."""

from __future__ import annotations

from typing import Any

from rich.prompt import IntPrompt, Prompt

from src.cli.banner import print_startup_banner
from src.prompts import EffortMode, get_effort_config, list_effort_modes, list_templates
from src.prompts.templates import register_all_templates
from src.services import rendering as R
from src.utils.settings import AibaSettings

_settings = AibaSettings()
register_all_templates()


def run_wizard() -> None:
    """Run the full interactive setup wizard and execute the agent."""
    print_startup_banner()
    try:
        mode = _mode_prompt()
        template_name = _template_prompt()
        effort = _effort_prompt()
        sub_agent_count = _settings.max_concurrent_sub_agents
        if mode == "swarm":
            sub_agent_count = _sub_agents_prompt()
        extra = _extra_prompt(mode)

        template = __import__("src.prompts", fromlist=["get_template"]).get_template(template_name)
        if not _settings.user_profile:
            R.console.print(
                R.panel_warning("\n  [yellow]⚠[/yellow]  USER_PROFILE is empty in .env — templates like job_search will have no context.\n"),
            )
            R.console.print("  [dim]Set USER_PROFILE in .env with your skills and experience.[/dim]\n")

        prompt = template.generate_prompt(_settings.user_profile, extra)
        _confirm_screen(mode, sub_agent_count, prompt)

        config = get_effort_config(effort)

        from src.agents.main_agent import run as run_orch
        from src.agents.sub_agent import run as run_agent

        if mode == "agent":
            result = run_agent(prompt=prompt, effort_mode=effort)
            agent_fn = run_agent
            agent_name = "Agent"
        else:
            result = run_orch(prompt=prompt, effort_mode=effort)
            agent_fn = run_orch
            agent_name = "Orchestrator"

        R.console.print("\n\n")
        R.render_markdown(result.output)

        session_settings: dict[str, Any] = {
            "mode": mode,
            "effort": effort.value,
            "template_name": template_name,
        }
        if mode == "swarm":
            session_settings["sub_agent_count"] = sub_agent_count

        from src.services.repl import run as run_repl
        run_repl(agent_fn, result, config, agent_name, session_settings)

    except Exception as exc:
        R.console.print(R.panel_error("Error", f"{type(exc).__name__}: {exc}"))


# ── Step functions ───────────────────────────────────────────────────


def _mode_prompt() -> str:
    """Choose agent or swarm mode."""
    R.console.print()
    R.divider()
    R.console.print("  [bold cyan]Step 1 — Select Mode[/bold cyan]")
    R.console.print()
    R.console.print("  [bold][1][/bold]  Agent   [dim]Single autonomous agent, full internet access[/dim]")
    R.console.print("          [dim]Best for focused tasks, single-domain research.[/dim]")
    R.console.print()
    R.console.print("  [bold][2][/bold]  Swarm   [dim]Orchestrated fleet of parallel sub-agents[/dim]")
    R.console.print("          [dim]Best for large-scale research, multi-hop mining.[/dim]")
    R.console.print()
    choice = Prompt.ask("  Enter 1 or 2", choices=["1", "2"])
    return "agent" if choice == "1" else "swarm"


def _template_prompt() -> str:
    """Choose a task template."""
    templates = list_templates()
    R.console.print()
    R.divider()
    R.console.print("  [bold cyan]Step 2 — Select Template[/bold cyan]")
    R.console.print()
    for i, tmpl in enumerate(templates, start=1):
        R.console.print(f"  [bold][{i}][/bold]  [cyan]{tmpl.name}[/cyan]")
        desc = tmpl.description
        from shutil import get_terminal_size
        w = get_terminal_size().columns
        while len(desc) > w - 10:
            cut = desc.rfind(" ", 0, w - 10)
            if cut == -1:
                cut = w - 10
            R.console.print(f"      [dim]{desc[:cut]}[/dim]")
            desc = desc[cut:].lstrip()
        R.console.print(f"      [dim]{desc}[/dim]")
        R.console.print()

    max_n = len(templates)
    choice = Prompt.ask(f"  Enter 1–{max_n}")
    try:
        idx = int(choice) - 1
        if 0 <= idx < max_n:
            return templates[idx].name
    except ValueError:
        pass
    R.console.print("  [red]✗[/red]  Invalid.")
    return _template_prompt()


def _effort_prompt() -> EffortMode:
    """Choose an effort level."""
    modes = list_effort_modes()
    R.console.print()
    R.divider()
    R.console.print("  [bold cyan]Step 3 — Effort Level[/bold cyan]")
    R.console.print()
    descriptions = {
        EffortMode.QUICK: "Fast & cheap — minimal tool calls, short responses. Good for quick lookups.",
        EffortMode.BALANCED: "Thorough & pragmatic — cross-check 2–3 sources. Good default.",
        EffortMode.MAX: "Exhaustive deep-dive — maximum tools, maximum tokens, maximum quality.",
    }
    for i, m in enumerate(modes, start=1):
        R.console.print(f"  [bold][{i}][/bold]  [cyan]{m.value}[/cyan]")
        R.console.print(f"      [dim]{descriptions[m]}[/dim]")
        R.console.print()

    max_n = len(modes)
    choice = Prompt.ask(f"  Enter 1–{max_n}")
    try:
        idx = int(choice) - 1
        if 0 <= idx < max_n:
            return modes[idx]
    except ValueError:
        pass
    R.console.print("  [red]✗[/red]  Invalid.")
    return _effort_prompt()


def _sub_agents_prompt() -> int:
    """Choose max concurrent sub-agents (swarm only)."""
    default = _settings.max_concurrent_sub_agents
    R.console.print()
    R.divider()
    R.console.print("  [bold cyan]Step 4 of 5 — Sub-Agent Pool[/bold cyan]")
    R.console.print()
    R.console.print("  How many sub-agents can run in parallel?  [dim]Range 1–50[/dim]")
    R.console.print("  Higher values = more throughput, more API tokens.")
    R.console.print()
    val = IntPrompt.ask("  Max sub-agents", default=default)
    if val < 1 or val > 50:
        R.console.print("  [red]✗[/red]  Must be between 1 and 50.")
        return _sub_agents_prompt()
    return val


def _extra_prompt(mode: str) -> str:
    """Optional extra notes appended to the template prompt."""
    step = "4 of 4" if mode == "agent" else "5 of 5"
    R.console.print()
    R.divider()
    R.console.print(f"  [bold cyan]Step {step} — Extra Notes[/bold cyan]")
    R.console.print()
    R.console.print("  The template already generated a detailed prompt.")
    R.console.print("  Add any extra context, URLs, or notes below (optional).")
    R.console.print("  [dim](Ctrl+D or empty line to skip)[/dim]")
    R.console.print()

    lines: list[str] = []
    try:
        while True:
            line = input()
            if line == "" and lines:
                break
            lines.append(line)
    except EOFError:
        pass
    return "\n".join(lines).strip()


def _confirm_screen(mode: str, sub_agent_count: int, prompt: str) -> None:
    """Show summary before launching."""
    preview = prompt[:100] + ("…" if len(prompt) > 100 else "")
    R.console.print()
    R.divider("═")
    R.console.print("  [bold purple]Launch Summary[/bold purple]")
    R.divider("═")
    R.console.print(R.badge("Mode", mode.upper()))
    if mode == "swarm":
        R.console.print(R.badge("Sub-agents", str(sub_agent_count)))
    R.console.print(R.badge("Prompt", preview))
    R.divider("═")
    R.console.print("\n\n\n")
