# Generated by OrchestKit Claude Plugin
# Created: 2026-07-14

"""Integration tests for config subcommand."""

from __future__ import annotations

from unittest.mock import patch

from typer.testing import CliRunner

from src.cli.main import app

runner = CliRunner()


def test_config_init_wizard_creates_env(tmp_path, monkeypatch):
    """config init without existing .env should create it."""
    monkeypatch.chdir(tmp_path)

    with patch("rich.prompt.Prompt.ask", return_value="test_value"):
        result = runner.invoke(app, ["config", "init"])
        assert result.exit_code == 0
        env_file = tmp_path / ".env"
        assert env_file.is_file()


def test_config_init_wizard_with_existing_env(tmp_path, monkeypatch):
    """config init with existing .env should preserve comments and update values."""
    monkeypatch.chdir(tmp_path)
    env_file = tmp_path / ".env"
    env_file.write_text("# comment line\nGEMINI_API_KEY=old_value\n", encoding="utf-8")

    from itertools import count
    counter = count()

    def _mock_ask(*args, **kwargs):
        i = next(counter)
        if i == 0:
            return "updated_key"
        return ""

    with patch("rich.prompt.Prompt.ask", side_effect=_mock_ask):
        result = runner.invoke(app, ["config", "init"])
        assert result.exit_code == 0

    content = env_file.read_text(encoding="utf-8")
    assert "# comment line" in content
    assert "GEMINI_API_KEY=updated_key" in content
