# Generated by OrchestKit Claude Plugin
# Created: 2026-07-14

"""`aiba config` subcommand — manage configuration."""

import typer

app = typer.Typer(
    name="config",
    help="Manage configuration",
    rich_markup_mode="rich",
)


@app.command()
def show() -> None:
    """Display current settings (secrets masked)."""
    from src.services import rendering as R
    from src.utils.settings import AibaSettings

    settings = AibaSettings()
    rows = []
    for field_name in AibaSettings.model_fields:
        value = getattr(settings, field_name)
        # Mask secrets
        if "api_key" in field_name or "token" in field_name or "password" in field_name:
            value = str(value)[:8] + "..." if value else "(empty)"
            display = R.Text(str(value), style="dim")
        elif value == "":
            display = R.Text("(empty)", style="dim")
        elif isinstance(value, bool):
            display = R.Text(str(value), style="green" if value else "dim")
        else:
            display = R.Text(str(value))
        rows.append((field_name, display))

    table = R.table(
        ("Setting", "Value"),
        rows,
        title="AIBA Configuration",
    )
    R.console.print(table)


@app.command(name="set")
def set_key(key_value: str = typer.Argument(..., help="KEY=VALUE pair to set")) -> None:
    """Set a configuration value in .env."""
    _set_impl(key_value)


def _set_impl(key_value: str) -> None:
    """Set a configuration value in .env."""
    from pathlib import Path

    from src.services import rendering as R
    from src.utils.settings import AibaSettings

    if "=" not in key_value:
        R.console.print(R.panel_error("Invalid format", "Use KEY=VALUE syntax"))
        raise typer.Exit(code=1)

    key, value = key_value.split("=", 1)
    key = key.strip().upper()
    value = value.strip()

    # Validate key exists in settings
    validation_alias: dict[str, str] = {}
    for f_name in AibaSettings.model_fields:
        alias = AibaSettings.model_fields[f_name].validation_alias
        if isinstance(alias, str) and alias:
            validation_alias[alias.upper()] = alias
        else:
            validation_alias[f_name.upper()] = f_name

    if key not in validation_alias:
        available = sorted(validation_alias.keys())
        R.console.print(
            R.panel_error(
                "Unknown setting",
                f"'{key}' is not a valid setting.\nAvailable: {', '.join(available)}",
            )
        )
        raise typer.Exit(code=1)

    env_path = Path(".env")
    lines = env_path.read_text(encoding="utf-8").splitlines(keepends=True) if env_path.is_file() else []

    # Use the validation alias (e.g. GEMINI_API_KEY) or the field name uppercased
    env_key = validation_alias.get(key, key)

    found = False
    for i, line in enumerate(lines):
        if line.strip().startswith(f"{env_key}=") or line.strip().startswith(f"{env_key} "):
            lines[i] = f"{env_key}={value}\n"
            found = True
            break

    if not found:
        lines.append(f"{env_key}={value}\n")

    env_path.write_text("".join(lines), encoding="utf-8")
    R.console.print(R.panel_success(f"Set {env_key}={value}"))


@app.command()
def list() -> None:
    """Show all available configuration keys with descriptions."""
    from src.services import rendering as R
    from src.utils.settings import AibaSettings

    rows = []
    for field_name, field_info in AibaSettings.model_fields.items():
        alias = field_info.validation_alias or field_name.upper()
        description = field_info.description or ""
        rows.append((alias, field_name, R.Text(description, style="dim")))

    table = R.table(
        ("Env Variable", "Field", "Description"),
        rows,
        title="Available Configuration Keys",
    )
    R.console.print(table)


@app.command()
def init() -> None:
    """Interactive configuration setup wizard."""
    from src.services import rendering as R
    from src.utils.settings import AibaSettings

    R.console.print(R.panel_info("Config Setup", "Enter values for each setting (empty to skip)"))
    _settings = AibaSettings()
    env_path = __import__("pathlib").Path(".env")

    existing_lines = env_path.read_text(encoding="utf-8").splitlines(keepends=True) if env_path.is_file() else []
    existing = {}
    for line in existing_lines:
        if "=" in line.strip() and not line.strip().startswith("#"):
            k, v = line.strip().split("=", 1)
            existing[k.strip()] = v.strip()

    with R.console.status("Walking through config..."):
        from rich.prompt import Prompt

        for field_name, field_info in AibaSettings.model_fields.items():
            alias = field_info.validation_alias or field_name.upper()
            description = field_info.description or ""
            current = existing.get(alias, "")

            R.console.print()
            R.console.print(f"[bold]{alias}[/bold]")
            R.console.print(f"[dim]{description}[/dim]")
            val = Prompt.ask("  Value", default=current or "")

            if val:
                found = False
                for i, line in enumerate(existing_lines):
                    if line.strip().startswith(f"{alias}="):
                        existing_lines[i] = f"{alias}={val}\n"
                        found = True
                        break
                if not found:
                    existing_lines.append(f"{alias}={val}\n")

        env_path.write_text("".join(existing_lines), encoding="utf-8")

    R.console.print(R.panel_success("Configuration updated"))
