# Generated by OrchestKit Claude Plugin
# Created: 2026-07-14

"""Tests for src.cli.banner — ASCII logo and startup display."""

from __future__ import annotations

from src.cli.banner import (
    _ASCII_LOGO,
    _generate_ascii_logo,
    print_session_resume_banner,
    print_startup_banner,
)


def test_ascii_logo_constant_is_non_empty():
    """The pre-built ASCII logo should be a non-empty string."""
    assert isinstance(_ASCII_LOGO, str)
    assert len(_ASCII_LOGO) > 0
    assert "C" in _ASCII_LOGO  # logo has chars


def test_generate_ascii_logo_returns_string():
    """_generate_ascii_logo should return a string."""
    result = _generate_ascii_logo(width=70)
    assert isinstance(result, str)
    assert len(result) > 0


def test_generate_ascii_logo_respects_width():
    """_generate_ascii_logo should produce lines roughly matching the requested width."""
    result = _generate_ascii_logo(width=40)
    assert isinstance(result, str)
    for _line in result.split("\n"):
        break  # smoke test — ensure iterable


def test_generate_ascii_logo_fallback_on_missing_file(monkeypatch):
    """When PNG is not found, should return the pre-built constant."""
    monkeypatch.setattr("src.cli.banner._LOGO_PATH", __import__("pathlib").Path("/nonexistent/logo.png"))
    result = _generate_ascii_logo()
    assert result == _ASCII_LOGO


def test_print_startup_banner_does_not_crash(capsys):
    """print_startup_banner should not raise."""
    try:
        print_startup_banner()
    except Exception as exc:
        raise AssertionError(f"print_startup_banner raised: {exc}") from exc


def test_print_session_resume_banner_does_not_crash(capsys):
    """print_session_resume_banner should not raise."""
    try:
        print_session_resume_banner("Agent", 5)
    except Exception as exc:
        raise AssertionError(f"print_session_resume_banner raised: {exc}") from exc


def test_generate_ascii_logo_with_non_rgba_image(monkeypatch, tmp_path):
    """Should handle non-RGBA images by converting."""
    from PIL import Image
    # Create a small RGB image (no alpha channel)
    img = Image.new("RGB", (10, 10), color="red")
    png_path = tmp_path / "test_rgb.png"
    img.save(png_path)
    monkeypatch.setattr("src.cli.banner._LOGO_PATH", png_path)
    result = _generate_ascii_logo(width=10)
    assert isinstance(result, str)
    assert len(result) > 0


def test_generate_ascii_fallback_on_exception(monkeypatch):
    """When PIL processing fails, should return the pre-built constant."""
    monkeypatch.setattr("PIL.Image.open", lambda _: (_ for _ in ()).throw(Exception("mock")))
    result = _generate_ascii_logo()
    assert result == _ASCII_LOGO
