# Generated by OrchestKit Claude Plugin
# Created: 2026-07-14

"""Tests for src.services.rendering — Rich-based rendering primitives."""

from __future__ import annotations

from src.services import rendering as R


def test_console_is_singleton():
    """console should be a Rich Console instance."""
    assert hasattr(R.console, "print")
    assert hasattr(R.console, "input")


def test_panel_error_returns_panel():
    """panel_error should return a Rich Panel."""
    panel = R.panel_error("Test Error", "Something went wrong")
    assert "Test Error" in str(panel.title)


def test_panel_success_returns_panel():
    """panel_success should return a Rich Panel."""
    panel = R.panel_success("All good")
    assert "All good" in str(panel.renderable)


def test_panel_info_returns_panel():
    """panel_info should return a Rich Panel."""
    panel = R.panel_info("Info", "Some information")
    assert "Info" in str(panel.title)


def test_panel_warning_returns_panel():
    """panel_warning should return a Rich Panel."""
    panel = R.panel_warning("Be careful")
    assert "Be careful" in str(panel.renderable)


def test_table_creates_table():
    """table() should create a Rich Table with given headers and rows."""
    tbl = R.table(("A", "B"), [("1", "2"), ("3", "4")], title="Test")
    assert tbl is not None
    assert tbl.columns[0].header == "A"
    assert tbl.columns[1].header == "B"


def test_badge_returns_string():
    """badge() should return a styled string."""
    result = R.badge("Mode", "swarm")
    assert "Mode" in result
    assert "swarm" in result


def test_divider_does_not_crash(capsys):
    """divider() should not raise."""
    try:
        R.divider()
    except Exception as exc:
        raise AssertionError(f"divider raised: {exc}") from exc


def test_hr_is_alias():
    """hr should be the same as divider."""
    assert R.hr is R.divider


def test_c_dict_present():
    """Legacy C dict should still be available."""
    assert "reset" in R.C
    assert "bold" in R.C
    assert "red" in R.C


def test_width_returns_int():
    """_width() should return a positive integer."""
    result = R._width()
    assert isinstance(result, int)
    assert result > 0
