# Generated by OrchestKit Claude Plugin
# Created: 2026-07-14

"""Tests for src.cli.status — live status display."""

from __future__ import annotations

from datetime import UTC, datetime

from src.cli.status import AgentStatus, agent_status_display


def test_agent_status_initialization():
    """AgentStatus should initialize with given values."""
    status = AgentStatus(agent_name="TestAgent", model_name="test-model")
    assert status.agent_name == "TestAgent"
    assert status.model_name == "test-model"
    assert status._tokens == 0
    assert status._cost == 0.0
    assert status._status_text == "Running..."
    assert status.start_time <= datetime.now(UTC)


def test_agent_status_update():
    """AgentStatus.update should update internal fields."""
    status = AgentStatus(agent_name="Agent")
    status.update(tokens=100, cost=0.05, status_text="Processing...")
    assert status._tokens == 100
    assert status._cost == 0.05
    assert status._status_text == "Processing..."


def test_agent_status_update_partial():
    """AgentStatus.update should handle partial updates."""
    status = AgentStatus()
    status.update(tokens=50)
    assert status._tokens == 50
    assert status._cost == 0.0  # unchanged


def test_build_table_returns_table():
    """_build_table should return a Rich Table."""
    status = AgentStatus(agent_name="A", model_name="M")
    table = status._build_table()
    assert table is not None
    # Table should have column for spinner, agent name
    assert table.columns is not None


def test_agent_status_display_context():
    """agent_status_display should return an AgentStatus context manager."""
    status = agent_status_display(agent_name="Agent", model_name="gemini-test")
    assert isinstance(status, AgentStatus)

    # Test context manager usage
    with status as s:
        assert s is not None
        s.update(tokens=10)


def test_agent_status_with_tokens_and_cost():
    """Status with tokens+cost should include them in the table."""
    status = AgentStatus(agent_name="Agent", model_name="M")
    status.update(tokens=500, cost=0.05)
    table = status._build_table()
    assert table is not None
    # Table __str__ gives a rich renderable repr, not user text
    # Just verify it doesn't crash and builds correctly
    assert table.columns is not None


def test_agent_status_status_text():
    """Custom status text should appear in the table."""
    status = AgentStatus()
    status.update(status_text="Custom message")
    table = status._build_table()
    assert table is not None
    assert table.columns is not None


def test_agent_status_elapsed_time():
    """Elapsed time should increase."""
    import time
    status = AgentStatus()
    table1 = str(status._build_table())
    time.sleep(0.1)
    table2 = str(status._build_table())
    # Just verify it doesn't crash
    assert table1 is not None
    assert table2 is not None
